### ISSUE TITLE
尝试了一下

### ISSUE THREAD

**Issue by luckypoem** [xuduo35/simpleproxy#1]
按你的readme,操作了一番，翻不了墙啊。怎么回事？
你自己亲测，能成功翻墙吗

**Comment by xuduo35** [comment]
不好意思，才看到。当然可以。你可以用netstat命令看看哪里的问题，是不是你vps防火墙没放开端口。

**Comment by luckypoem** [comment]
hi.
其实它这个程序的翻墙原理没完全搞懂。
在linux vps上：
root@host ~]# lsof -i:8893
[root@host ~]# 

竟然没有进程监听8893端口，这是怎么回事？这里https://github.com/xuduo35/simpleproxy/blob/master/testproxy.js 的第三行不是显示serverport为8893吗？我没改testproxy.js 文件。

**Comment by xuduo35** [comment]
web browser -> localhost:8893 -> remote vps:8894。明白了吗
